building and testing the pipeline at the same time

diff --git a/local-pipeline/local_ci-cd b/local-pipeline/local_ci-cd
--- a/local-pipeline/local_ci-cd
+++ b/local-pipeline/local_ci-cd
@@ -42,6 +42,27 @@ if [ "$playbooks" = true ]; then
     echo "========================================"
 fi
 
+backup=false
+for file in "$playbook_dir/"config_backup*.yml "$playbook_dir/"config_backup*.yaml; do
+    if [ -f "$file" ]; then
+        backup=true
+        break
+    fi
+done
+
+if [ "$backup" = true ]; then
+    echo "Runnning Ansible Backups..."
+    if ! uv run ansible-playbook \
+        -i inventory/inventory \
+        playbooks/"$file"; then
+        echo "Ansible backup failed, exiting pipeline"
+        echo "========================================"
+        exit 1
+    fi
+    echo "Ansible backup completed successfully."
+    echo "========================================"
+fi
+
 echo "[2/4] Running tests..."
 
 # Replace this with your project's test command.
