building and testing the pipeline at the same time

diff --git a/local-pipeline/local_ci-cd-post b/local-pipeline/local_ci-cd-post
--- a/local-pipeline/local_ci-cd-post
+++ b/local-pipeline/local_ci-cd-post
@@ -10,29 +10,29 @@ tests_dir="$repo_root/tests"
 
 log_dir="$repo_root/logs"
 ts=$(date '+%Y%m%d-%H%M%S')
-ansible_log_file="$log_dir/ansible-cicd-$ts-$$.log"
-pyats_log_file="$log_dir/pyats-cicd-$ts-$$.log"
+ansible_log_file="$log_dir/ansible-post-cicd-$ts-$$.log"
+pyats_log_file="$log_dir/pyats-post-cicd-$ts-$$.log"
 
 cd "$repo_root"
 
 echo ""
 echo "========================================"
-echo "Local CI/CD started"
-echo "Repository: $repo_root"
-echo "Branch:     $branch"
-echo "Commit:     $commit"
+echo "[post-commit] Local CI/CD started"
+echo "[post-commit] Repository: $repo_root"
+echo "[post-commit] Branch:     $branch"
+echo "[post-commit] Commit:     $commit"
 echo "========================================"
 
 # sync python environment
-echo ""
-echo "Sync'ing python environment..."
-echo ""
-uv python install 3.14
-uv sync --python 3.14
-echo ""
-echo "Python environment sync complete."
-echo "========================================"
-echo ""
+# echo ""
+# echo "Sync'ing python environment..."
+# echo ""
+# uv python install 3.14
+# uv sync --python 3.14
+# echo ""
+# echo "Python environment sync complete."
+# echo "========================================"
+# echo ""
 
 playbooks=false
 for file in "$playbook_dir"/*.yml "$playbook_dir"/*.yml; do
@@ -43,57 +43,57 @@ for file in "$playbook_dir"/*.yml "$playbook_dir"/*.yml; do
 done
 
 # Ansible syntax check
-if [[ "$playbooks" = true ]]; then
-    echo "Running Ansible Syntax Check..."
-    echo ""
-
-    if ! find playbooks -maxdepth 1 -type f \
-        \( -name '*.yml' -o -name '*.yaml' \) \
-        -exec uv run ansible-playbook \
-        --syntax-check \
-        -i inventory/inventory.yml {} + >>"$ansible_log_file" 2>&1; then
-        echo "Ansible syntax check failed, exiting pipeline"
-        echo "========================================"
-        echo ""
-        exit 1
-    fi
-    echo ""
-    echo "Ansible syntax check successful"
-    echo "========================================"
-    echo ""
-fi
+# if [[ "$playbooks" = true ]]; then
+#     echo "Running Ansible Syntax Check..."
+#     echo ""
+#
+#     if ! find playbooks -maxdepth 1 -type f \
+#         \( -name '*.yml' -o -name '*.yaml' \) \
+#         -exec uv run ansible-playbook \
+#         --syntax-check \
+#         -i inventory/inventory.yml {} + >>"$ansible_log_file" 2>&1; then
+#         echo "Ansible syntax check failed, exiting pipeline"
+#         echo "========================================"
+#         echo ""
+#         exit 1
+#     fi
+#     echo ""
+#     echo "Ansible syntax check successful"
+#     echo "========================================"
+#     echo ""
+# fi
 
 # Ansible backups
-backup=false
-backup_file=""
-for file in "$playbook_dir/"config_backup*.yml "$playbook_dir/"config_backup*.yaml; do
-    if [[ -f "$file" ]]; then
-        backup=true
-        backup_file=${file##*/}
-        break
-    fi
-done
-
-if [[ "$backup" = true ]]; then
-    echo "Runnning Ansible Backups..."
-    echo ""
-    if ! uv run ansible-playbook \
-        -i inventory/inventory.yml \
-        "$playbook_dir"/"$backup_file" >>"$ansible_log_file" 2>&1; then
-        echo "Ansible backup failed, exiting pipeline"
-        echo "========================================"
-        echo ""
-        exit 1
-    fi
-    echo "Ansible backups completed successfully."
-    echo "Backups saved to $repo_root/backups"
-    echo "========================================"
-    echo ""
-fi
+# backup=false
+# backup_file=""
+# for file in "$playbook_dir/"config_backup*.yml "$playbook_dir/"config_backup*.yaml; do
+#     if [[ -f "$file" ]]; then
+#         backup=true
+#         backup_file=${file##*/}
+#         break
+#     fi
+# done
+#
+# if [[ "$backup" = true ]]; then
+#     echo "Runnning Ansible Backups..."
+#     echo ""
+#     if ! uv run ansible-playbook \
+#         -i inventory/inventory.yml \
+#         "$playbook_dir"/"$backup_file" >>"$ansible_log_file" 2>&1; then
+#         echo "Ansible backup failed, exiting pipeline"
+#         echo "========================================"
+#         echo ""
+#         exit 1
+#     fi
+#     echo "Ansible backups completed successfully."
+#     echo "Backups saved to $repo_root/backups"
+#     echo "========================================"
+#     echo ""
+# fi
 
 # Ansible playbooks
 if [[ "$playbooks" = true ]]; then
-    echo "Running Ansible playbooks..."
+    echo "[post-commit] Running Ansible playbooks..."
     echo ""
     for playbook in playbooks/*.yml playbooks/*.yaml; do
         [[ -f "$playbook" ]] || continue
@@ -104,19 +104,19 @@ if [[ "$playbooks" = true ]]; then
             ;;
         esac
 
-        echo "Running: $playbook"
+        echo "[post-commit] Running: $playbook"
 
         if ! uv run ansible-playbook \
             -i inventory/inventory.yml \
             "$playbook" >>"$ansible_log_file" 2>&1; then
-            echo "Playbook failed: $playbook"
+            echo "[post-commit] Playbook failed: $playbook"
             echo "========================================"
             echo ""
             exit 1
         fi
     done
     echo ""
-    echo "Ansible playbooks completed successfully."
+    echo "[post-commit] Ansible playbooks completed successfully."
     echo "========================================"
     echo ""
 fi
@@ -124,21 +124,21 @@ fi
 # pyATS tests
 pyats_status=0
 if [[ -f "$tests_dir"/job.py ]]; then
-    echo "Running pyATS tests..."
+    echo "[post-commit] Running pyATS tests..."
     echo ""
 
     if uv run pyats run job tests/job.py --no-mail --no-archive >>"$pyats_log_file" 2>&1; then
-        echo "pyATS tests completeed successfully."
+        echo "[post-commit] pyATS tests completeed successfully."
         echo "========================================"
         echo ""
     else
         pyats_status=$?
-        echo "pyATS tests failed with status $pyats_status"
+        echo "[post-commit] pyATS tests failed with status $pyats_status"
         echo "========================================"
         echo ""
     fi
 fi
 
-echo "Local CI/CD completed successfully for $branch at $commit."
+echo "[post-commit] Local CI/CD completed successfully for $branch at $commit."
 echo "========================================"
 echo ""
